#ItemCommands v1.0.0 created by cj89898
#
#Example config
#
#items:
#  pickaxes: -- Name can be anything
#    materials:
#      - wood_pickaxe
#      - stone_pickaxe
#      - iron_pickaxe
#      - gold_pickaxe
#      - diamond_pickaxe
#    left_click_commands:
#      - 'spawn'
#    right_click_commands:
#      - 'spawn'
#    disabled_worlds:
#      - world_nether
#   left_click_cooldown: 20 #Based on ticks (20 per second)
#   right_click_cooldown: 20 #Based on ticks (20 per second)


items:
  pickaxes:
    materials:
      - wood_pickaxe
      - stone_pickaxe
      - iron_pickaxe
      - gold_pickaxe
      - diamond_pickaxe
    left_click_commands:
      - 'say hi'
    right_click_commands:
      - 'say hello'
    disabled_worlds:
      - world_nether
    left_click_cooldown: 20
    right_click_cooldown: 20